name: github-actions
on: push

jobs:
  my_first_job:
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/checkout@v1
     - name: My first step
     - uses: actions/Test@latest
     - name: Test
